# Generated by Django 4.2.5 on 2023-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.technology'),
        ),
    ]
