# Generated by Django 4.2.5 on 2023-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(to='blogpost.post'),
        ),
    ]
