# Generated by Django 4.2.6 on 2023-12-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_postcomment_updated_at_alter_postcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
