# Generated by Django 4.2.6 on 2024-06-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogpost", "0005_postcomment_edited"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
