# Generated by Django 4.2.5 on 2023-10-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_remove_category_posts_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blogpost.category'),
        ),
    ]
