# Generated by Django 5.0.6 on 2024-07-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0008_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="parent_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blogpost.postcomment",
            ),
        ),
    ]
